"""Application settings (SPEC §13.1)."""

from __future__ import annotations

from functools import lru_cache
from typing import Literal

from pydantic import EmailStr, Field, SecretStr, field_validator
from pydantic_settings import BaseSettings, SettingsConfigDict


def _normalize_db_url(url: str) -> str:
    """Normalize sync SQLite URLs onto the aiosqlite driver."""
    if url.startswith("sqlite+aiosqlite://"):
        return url
    if url.startswith("sqlite://"):
        return "sqlite+aiosqlite://" + url.removeprefix("sqlite://")
    return url


class Settings(BaseSettings):
    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        env_prefix="VAGG_CORE_",
        extra="ignore",
    )

    # ----- Runtime -----
    environment: Literal["dev", "staging", "production", "test"] = "dev"
    log_level: Literal["DEBUG", "INFO", "WARNING", "ERROR"] = "INFO"
    bind_host: str = "0.0.0.0"  # noqa: S104 — serves on all interfaces by design
    bind_port: int = 8443

    # ----- Database -----
    # SPEC §2.1: SQLite (WAL mode). Path is relative to working dir or absolute.
    database_url: SecretStr = SecretStr("sqlite+aiosqlite:///./vagg-core.db")

    @field_validator("database_url", mode="before")
    @classmethod
    def _normalize(cls, raw: str | SecretStr) -> str:
        value = raw.get_secret_value() if isinstance(raw, SecretStr) else raw
        return _normalize_db_url(value)

    # ----- Auth -----
    # Bootstrap admin (SPEC §13.1). Single admin per install; multi-admin in a later phase.
    # Default uses ``.example`` (RFC 2606 reserved TLD); ``.local`` is rejected by
    # email-validator as a special-use name.
    admin_email: EmailStr = "admin@vagg.example"
    # argon2 hash. Generated by `python -m vagg_core.scripts.hash_password`.
    admin_password_hash: SecretStr

    # JWT signing secret (HMAC-SHA256). Generated at install (SPEC §13.1).
    jwt_secret: SecretStr
    jwt_access_ttl_seconds: int = 15 * 60
    jwt_refresh_ttl_seconds: int = 7 * 24 * 3600
    jwt_issuer: str = "vagg-core"

    # ----- Domain -----
    # SPEC §4.6: 10.200.0.0/16 reserved for virtual range. Configurable in case of conflict.
    virtual_range: str = "10.200.0.0/16"
    domain: str = Field(default="vpn.example.local")

    # ----- License (Phase 1 integration; full enforcement in later phase) -----
    license_key: SecretStr | None = None
    license_server: str = "https://licensing.vagg.io"


@lru_cache(maxsize=1)
def get_settings() -> Settings:
    """Memoized Settings. Tests inject a fresh Settings via dependency override."""
    return Settings()
