"""Application settings (SPEC §13.1)."""

from __future__ import annotations

from functools import lru_cache
from pathlib import Path
from typing import Literal

from pydantic import EmailStr, Field, SecretStr, field_validator
from pydantic_settings import BaseSettings, SettingsConfigDict


def _normalize_db_url(url: str) -> str:
    """Normalize sync SQLite URLs onto the aiosqlite driver."""
    if url.startswith("sqlite+aiosqlite://"):
        return url
    if url.startswith("sqlite://"):
        return "sqlite+aiosqlite://" + url.removeprefix("sqlite://")
    return url


class Settings(BaseSettings):
    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        env_prefix="VAGG_CORE_",
        extra="ignore",
    )

    # ----- Runtime -----
    environment: Literal["dev", "staging", "production", "test"] = "dev"
    log_level: Literal["DEBUG", "INFO", "WARNING", "ERROR"] = "INFO"
    bind_host: str = "0.0.0.0"  # noqa: S104 — serves on all interfaces by design
    bind_port: int = 8443

    # ----- Database -----
    # SPEC §2.1: SQLite (WAL mode). Path is relative to working dir or absolute.
    database_url: SecretStr = SecretStr("sqlite+aiosqlite:///./vagg-core.db")

    @field_validator("database_url", mode="before")
    @classmethod
    def _normalize(cls, raw: str | SecretStr) -> str:
        value = raw.get_secret_value() if isinstance(raw, SecretStr) else raw
        return _normalize_db_url(value)

    # ----- Auth -----
    # Bootstrap admin (SPEC §13.1). Single admin per install; multi-admin in a later phase.
    # Default uses ``.example`` (RFC 2606 reserved TLD); ``.local`` is rejected by
    # email-validator as a special-use name.
    admin_email: EmailStr = "admin@vagg.example"
    # argon2 hash. Generated by `python -m vagg_core.scripts.hash_password`.
    admin_password_hash: SecretStr

    # JWT signing secret (HMAC-SHA256). Generated at install (SPEC §13.1).
    jwt_secret: SecretStr
    jwt_access_ttl_seconds: int = 15 * 60
    jwt_refresh_ttl_seconds: int = 7 * 24 * 3600
    jwt_issuer: str = "vagg-core"

    # Fernet key (32 bytes urlsafe-base64) pra encryption-at-rest de secrets
    # sensíveis tipo TOTP seeds. Em prod é obrigatória; em dev/test cai pra
    # derivação HKDF do jwt_secret (ver core.crypto).
    crypto_key: SecretStr | None = None

    # ----- Domain -----
    # SPEC §4.6: 10.200.0.0/16 reserved for virtual range. Configurable in case of conflict.
    virtual_range: str = "10.200.0.0/16"
    domain: str = Field(default="vpn.example.local")

    # ----- License (Phase 1 integration; full enforcement in later phase) -----
    license_key: SecretStr | None = None
    license_server: str = "https://licensing.vagg.io"

    # ----- Tunnels (SPEC §5.2 / Fase 3) -----
    tunnels_config_dir: Path = Path("/var/lib/vagg/clients")
    tunnels_sockets_dir: Path = Path("/var/run/vagg")
    tunnels_image_tag: str = "dev"
    # ``host`` shares the host's network namespace so tun-X is visible to host
    # iptables (SPEC §3.4 + §4.3). Override only for testing.
    tunnels_network_name: str = "host"
    tunnels_restart_policy: str = "unless-stopped"
    tunnels_controller_timeout_s: float = 2.0
    tunnels_health_enabled: bool = True
    tunnels_health_interval_s: float = 30.0
    docker_host: str | None = None  # passa-thru pra DOCKER_HOST

    # ----- Networking apply (SPEC §4.2 / §4.3 / Fase 4) -----
    # Disabled by default in dev/test; the installer sets it to true.
    network_apply_enabled: bool = False
    rt_tables_path: Path = Path("/etc/iproute2/rt_tables")

    # ----- Portal de Transparência (SPEC §5.6 / Fase 11) -----
    portal_enabled: bool = True
    portal_signing_key_path: Path = Path("/var/lib/vagg/portal-signing-key.pem")

    # ----- DNS (SPEC §4.4 / §5.3 / Fase 6) -----
    # Disabled by default — installer sets ``dns_enabled=true`` and points
    # ``dns_config_path`` at the volume shared with the vagg-dns container.
    dns_enabled: bool = False
    dns_config_path: Path = Path("/etc/coredns/Corefile")
    dns_container_name: str = "vagg-dns"
    dns_default_forwarders: str = "8.8.8.8,8.8.4.4"


@lru_cache(maxsize=1)
def get_settings() -> Settings:
    """Memoized Settings. Tests inject a fresh Settings via dependency override."""
    return Settings()
