"""Generate a fresh Ed25519 keypair.

The PRIVATE key is loaded by the license server from the env var
``VAGG_LICENSE_JWT_PRIVATE_KEY_PEM``. Treat it as production secret.

The PUBLIC key gets embedded in vagg-core as a Python constant (SPEC §6.6) — use
``--emit-pubkey-py`` to dump in the right format for vagg-core to import.

Usage::

    vagg-license-keypair                       # prints both keys, prompts to confirm
    vagg-license-keypair --out-dir .secrets    # writes to files
    vagg-license-keypair --emit-pubkey-py      # prints a Python module body for vagg-core
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey


def _generate() -> tuple[bytes, bytes]:
    private = Ed25519PrivateKey.generate()
    private_pem = private.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption(),
    )
    public_pem = private.public_key().public_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PublicFormat.SubjectPublicKeyInfo,
    )
    return private_pem, public_pem


def _emit_pubkey_module(public_pem: bytes) -> str:
    pem_str = public_pem.decode("utf-8").rstrip()
    return (
        '"""Auto-generated by vagg-license-keypair. Embedded public key (SPEC §6.6)."""\n'
        "\n"
        "LICENSE_PUBLIC_KEY_PEM = b\"\"\"" + pem_str + "\n\"\"\"\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate Ed25519 keypair for license JWT signing.")
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=None,
        help="Write private.pem and public.pem to this directory (must not exist)",
    )
    parser.add_argument(
        "--emit-pubkey-py",
        action="store_true",
        help="Print a Python module body containing the public key as a bytes constant",
    )
    args = parser.parse_args()

    private_pem, public_pem = _generate()

    if args.out_dir is not None:
        out: Path = args.out_dir
        if out.exists() and any(out.iterdir()):
            print(f"Refusing to write into non-empty directory: {out}", file=sys.stderr)
            return 2
        out.mkdir(parents=True, exist_ok=True)
        (out / "private.pem").write_bytes(private_pem)
        (out / "public.pem").write_bytes(public_pem)
        print(f"Wrote {out / 'private.pem'} (mode 600 recommended)")
        print(f"Wrote {out / 'public.pem'}")
        return 0

    if args.emit_pubkey_py:
        print(_emit_pubkey_module(public_pem))
        return 0

    print("=== PRIVATE KEY (set as VAGG_LICENSE_JWT_PRIVATE_KEY_PEM, keep secret) ===")
    print(private_pem.decode("utf-8"))
    print("=== PUBLIC KEY (set as VAGG_LICENSE_JWT_PUBLIC_KEY_PEM, also embed in vagg-core) ===")
    print(public_pem.decode("utf-8"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
